# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: facfd8c5fc5b0fd2b24fbf82c87f292963c76b8ffee8cb514549f4d0e9473379410398362889a7b50befc051a49d681190d1328d8f4e3d0c74626d5767e28157

test:
  secret_key_base: 150c3e56c092500a36bfce08226a8c39d07ee899199eaed0c534b00f8851856b82bc347aa5a8daeb97e087e009c1550732afa0fa95f511c316c02c91cfc11ed1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
